# Generated by Django 4.0.4 on 2022-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.PositiveIntegerField(unique=True)),
                ('available', models.BooleanField(default=True)),
                ('locationX', models.IntegerField(blank=True, null=True)),
                ('locationY', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
